enum CharacterFlag
{
	eCF_hideLeftWeapon				= 1 << 0,
	eCF_hideRightWeapon				= 1 << 1,
	eCF_leftWeaponOut				= 1 << 2,
	eCF_rightWeaponOut				= 1 << 3,
	eCF_showBattleHelmet			= 1 << 4,
	eCF_rollupMode					= 1 << 5,
	eCF_hideCarriageHorse0			= 1 << 6,
	eCF_hideCarriageHorse1			= 1 << 7,
	eCF_hideCarriageHorse2			= 1 << 8,
	eCF_hideCarriageHorse3			= 1 << 9,
	eCF_underwearMode				= 1 << 10,
	eCF_disableBattleHelmet			= 1 << 11,
	eCF_hideAwakenWeapon			= 1 << 12,
	eCF_awakenWeaponOut				= 1 << 13,
	eCF_hideHelmet					= 1 << 14,
	eCF_hideCloak					= 1 << 15,
	eCF_isBattleWeaponType			= 1 << 16,
};
