enum eMessageList
	ePML_patcherAlreadyRun = 0,
	ePML_blackDesertAlreadyRun,	
	ePML_failBlackDesertExcute,

	ePML_patchCompleted,
	ePML_downloding,
	ePML_restartPatcher,
	ePML_pleaseRestart,
	ePML_recoverPack,
	ePML_integrityData,
	ePML_undefinedMessage,
	ePML_recoveryQuestion,
	ePML_alreadyWork,
	ePML_quitQuestion,
	ePML_startUpdate,
	ePML_downloadSize,
	ePML_deletePack,
	ePML_estimatedTime,
	ePML_second,
	ePML_minute,
	ePML_hour,
	ePML_moreThan60,
	ePML_lessThanSecond,
	ePML_quit,
	ePML_fileRecovery,
	ePML_play,
	ePML_playTip,

	ePML_checkingLauncherVersion,
	ePML_downloadServerMeta,
	ePML_createPack,
	ePML_parseClientMeta,
	ePML_compareMeta,
	ePML_buildDownloadList,
	ePML_downloadPack,
	ePML_extractPack,
	ePML_buildFileMap,
	ePML_cleanupTemp,
	ePML_gatherPack,
	ePML_prepareMetaInfo,
	ePML_prepareFileMap,
	ePML_outputMeta,

	ePML_errMsgDoRecoveryFiles,

	// PAPatcherLib2���� ���
	ePML_failedToPatchLauncher,
	ePML_failedToCreateTempFolder,
	ePML_downloadingSsvi,
	ePML_failedToDownloadSsvi,
	ePML_failedToParseSsvi,
	ePML_failedToCreateCsvi,
	ePML_upToDate,
	ePML_reinstall_old,
	ePML_invalidClientVersion,
	ePML_failedToDeleteFile,
	ePML_applyingPatch,
	ePML_failedToDownloadPatch,
	ePML_failedToApplyPatch,
	ePML_failedToUpdateVersion,
	ePML_failedToVerify,
	ePML_failedToPatch,
	ePML_verifyingRtPatch,
	ePML_applyingRtPatch,
	ePML_downloadingPatchData,
	ePML_notifyCriticalError,

	ePML_prepareCleanup,
	ePML_removingBinary,
	ePML_downloadingBinary,
	ePML_decompressingBinary,
	ePML_downloadingMetaData,
	ePML_buildingFileListToUpdate,
	ePML_downloadingPackageFiles,
	ePML_cleanupCompleted,
	ePML_cleanupEstimated,
	ePML_failedToCreateCleanupFlag,
	ePML_failedToDownloadBinaryPack,
	ePML_failedToDecompressBinaryPack,
	ePML_failedToDownloadMetaFile,
	ePML_failedToDownloadPackage,
	ePML_failedToBuildFileListToUpdate,
	ePML_failedToCleanupPackage,
	ePML_failedToVerifyPackages,
	ePML_askToCleanup,
	

	//	���� ��ó���� ���
	ePML_failConnectServer,
	ePML_failDownloadPatcher,
	ePML_failRenamePatcher,
	ePML_install2010RedPackX86,
	ePML_install2010RedPackX64,
	ePML_failOpenWorkPath,
	ePML_notEnoughDiskSpace,
	ePML_alreadyRunLauncher,
	ePML_alreadyRunPatcher,
	ePML_failUpdatePatcherVer,
	ePML_failUpdateVerInfo,
	ePML_failCreateProcess,

	ePML_MAX,
};
