enum ESTARLIBTYPE
{
    STLT_DISABLE    = 0,

    STLT_CROSS,
    STLT_CROSSFILTER,
    STLT_SNOWCROSS,
    STLT_VERTICAL,
    NUM_BASESTARLIBTYPES,

    STLT_SUNNYCROSS = NUM_BASESTARLIBTYPES,

    NUM_STARLIBTYPES,
};
