enum PA_EFFECT_BLEND
{
	EBD_ADD = 0,
	EBD_ADD_SOFT,
	EBD_ADD_NOALPHA,
	EBD_ALPHABLEND,
	EBD_ALPHABLEND_DISTORTION,
	EBD_ALPHABLEND_ADD,
	EBD_ALPHABLEND_NOWEATHER,
	EBD_ADD_NOLIGHT,
	EBD_ADD_SOFT_NOLIGHT,
	EBD_ADD_NOALPHA_NOLIGHT,
	EBD_ALPHABLEND_ADD_NOLIGHT,
	EBD_MAX,
	EBD_NULL = -1,
};
