enum PA_UI_CONTROL_TYPE
{
	PA_UI_CONTROL_PANEL = 0,
	PA_UI_CONTROL_STATIC,
	PA_UI_CONTROL_STATICTEXT,
	PA_UI_CONTROL_BUTTON,
	PA_UI_CONTROL_CHECKBUTTON,
	PA_UI_CONTROL_EDIT,
	PA_UI_CONTROL_RADIOBUTTON,
	PA_UI_CONTROL_SLIDER,
	PA_UI_CONTROL_PROGRESS,				// Not Use
	PA_UI_CONTROL_PROGRESS2,
	PA_UI_CONTROL_CIRCULAR_PROGRESS,
	PA_UI_CONTROL_COMBOBOX,
	PA_UI_CONTROL_LIST,
	PA_UI_CONTROL_SCROLL,
	PA_UI_CONTROL_CHAT,
	PA_UI_CONTROL_SCROLLWND,			// Not Use
	PA_UI_CONTROL_SCROLLWND2,			// Not Use
	PA_UI_CONTROL_POPUP,				// Not Use
	PA_UI_CONTROL_TREE,
	PA_UI_CONTROL_FRAME,
	PA_UI_CONTROL_FRAME_CONTENT,
	PA_UI_CONTROL_NUMSTATIC,
	PA_UI_CONTROL_SLIDESTATIC,
	PA_UI_CONTROL_GROUPLIST,
	PA_UI_CONTROL_MOVIECLIP,			// Not Use
	PA_UI_CONTROL_WEBCONTROL,
	PA_UI_CONTROL_MULTILINETEXT,		// Not Use
	PA_UI_CONTROL_MULTILINEEDIT,
	PA_UI_CONTROL_LAST,			// ��Ʈ���� �ƴ϶� ENUM �� �������̴�.
};
