enum PA_UI_TOOLTIP_TYPE
{
	PA_UI_TOOLTIP_NONE,
	PA_UI_TOOLTIP_NORMAL,
	PA_UI_TOOLTIP_SKILL,
	PA_UI_TOOLTIP_ITEM,
	PA_UI_TOOLTIP_BUFF,
	PA_UI_TOOLTIP_ACTOR,

	PA_UI_TOOLTIP_NPC_RELATION,
	PA_UI_TOOLTIP_PLANT_RECIPE,

	// 	PA_UI_TOOLTIP_SERVANT,
};
