enum PA_UI_TOOLTIP_ALIGN
{
	PA_UI_TOOLTIP_ALIGN_UNDEFINED,
	PA_UI_TOOLTIP_ALIGN_RIGHT,
	PA_UI_TOOLTIP_ALIGN_LEFT,
	PA_UI_TOOLTIP_ALIGN_TOP,
	PA_UI_TOOLTIP_ALIGN_BOTTOM,
	PA_UI_TOOLTIP_ALIGN_TOP_CENTER,
};
