enum PACharacterTextureIndex
{
	CTI_INDEX_DIFFUSE = 0,
	CTI_INDEX_NORMAL,
	CTI_INDEX_SPEC,
	CTI_INDEX_EM,
	
	CTI_INDEX_MASK,
	CTI_INDEX_MASK_DETAIL,
	CTI_INDEX_WRINKLE,
	CTI_INDEX_STRESS,
	CTI_INDEX_DETAIL0,
	CTI_INDEX_DETAIL1,
	CTI_INDEX_DETAIL2,

	CTI_INDEX_HEIGHT,
	CTI_INDEX_BODYHEIGHT,
	
	CTI_INDEX_MAX,
};
