enum PAConstantBufferType
{
	PCBT_WEATHER = 0,
	PCBT_FRUSTUM,
	PCBT_FULLSCENEDIRECTION,
	PCBT_FULLSCENECONST,

	PCBT_FINAL,
	PCBT_BLOOM,
	PCBT_REFLECT,
	PCBT_POINTBLUR,
	PCBT_COPYTOBACKBUFFER,

	PCBT_CHARACTER,
	PCBT_CHARACTER_UV,
	PCBT_CHARACTER_SCENE,
	PCBT_CHARACTER_LIGHTAO,
	PCBT_CHARACTER_VELOCITY,
	PCBT_TATTOO,

	PCBT_OBJECT,
	PCBT_OBJECT_SCENE,
	PCBT_WATER,
	PCBT_WATER_SCENE,
	PCBT_DECAL,

	PCBT_TREE_COMMON,
	PCBT_TREE_SHADOW,
	PCBT_TREE_BILLBOARD,

	PCBT_TREE_WIND,

	PCBT_GRASS_IMPACT,
	PCBT_GRASS_INTERSECT,
	PCBT_WATER_INTERSECT,

	PCBT_CLOUD,

	PCBT_RAIN,
	PCBT_RAIN_FAR,
	PCBT_RAIN_ROOF,
	
	PCBT_UI,
	PCBT_INGAMEUI,

	PCBT_AALINE,
	PCBT_AALINE_SCENE,

	PCBT_LOCAL_WIND,
	PCBT_LOCAL_WET,

	PCBT_LIGHT_SCENE,
	PCBT_LIGHT_INSTANCE,
	PCBT_LIGHT_INSTANCE_SHADOW,
	PCBT_LIGHT_AMBIENT,
	PCBT_LIGHT_SCATTER,
	PCBT_LIGHT_INFO,
	PCBT_LIGHT_BRIGHT,

	PCBT_SHADOW,
	PCBT_SHADOW_AO,
	PCBT_SHADOW_DYNAMIC,
	PCBT_SHADOW_VIEW,

	PCBT_WORLDMAP_COMMON,
	PCBT_WORLDMAP_TERRAIN,
	PCBT_WORLDMAP_BOX,
	PCBT_WORLDMAP_OBJECT,

	PCBT_TERRAIN_COMMON,
	PCBT_TERRAIN_SCENE,
	PCBT_TERRAIN_FAR,
	PCBT_TERRAIN_REGION,

	PCBT_EFFECT_SCENE,
	PCBT_EFFECT_LINETRAIL,

	PCBT_FORWARDPLUS,

	PCBT_MAX
};
