enum PAEffectSpawnPositionType
{
	ESPT_POSITION,
	ESPT_BOX,
	ESPT_SPHERE,
	ESPT_CYLINDER,
	ESPT_CONE,
	ESPT_CYLINDER_ABSX,
	ESPT_CYLINDER_ABSZ,
	ESPT_CYLINDER_ABSXZ,
	ESPT_CIRCLE_RIBBON,
	ESPT_MAX,
};
