enum PAEffectSpawnVelocityType
{
	ESVT_VALUE,
	ESVT_BOX,
	ESVT_SPHERE_SURFACE,
	ESVT_CONE,
	ESVT_RANDOM,
	ESVT_SIN,
	ESVT_COS,
	ESVT_SPHERE_VOLUME,
	ESVT_CYLINDER_SURFACE,
	ESVT_CYLINDER_VOLUME,
	ESVT_CYLINDER_TORNADO,
	ESVT_CYLINDER_HURRICANE,
	ESVT_MAX,
};
