enum PAObjectTextureIndex
{
	OTI_INDEX_DIFFUSE = 0,
	OTI_INDEX_NORMAL,
	OTI_INDEX_PARALLAX,
	OTI_INDEX_SPEC,
	OTI_INDEX_EM,
	
	OTI_INDEX_DETAIL_DIFFUSE,
	OTI_INDEX_DETAIL_NORMAL,
	OTI_INDEX_REPLACE_LAST = OTI_INDEX_DETAIL_NORMAL,	// Blend ����

	OTI_INDEX_LARGE_NORMAL,
	OTI_INDEX_BLEND_DIFFUSE,
	OTI_INDEX_BLEND_NORMAL,
	OTI_INDEX_BLEND_SPEC,

	OTI_INDEX_MAX,
};
