enum PASceneShaderType
{
	PSST_SKY,
	PSST_SEA,
	PSST_SEA2,
	PSST_SEA3,
	PSST_SEA_FLOW,
	PSST_SEA_HEIGHT_CALC,
	PSST_OCEAN_SURFACE,
	PSST_VOLUMEFOG,
	PSST_VOLUMEWATER,
	//PSST_WEATHER,
	PSST_SKY_CLOUDFAR,
	PSST_SKY_CLOUDDENSITY,
	PSST_SKY_CLOUDBLUR,
	PSST_CLOUDFAR_OCCLUSION,

	PSST_HEIGHTMAP,
	//PSST_HEIGHTMAP_MATERIAL,

	//PSST_TERRAIN_SCENE,
	//PSST_TERRAIN_SCENE_X,
	//PSST_TERRAIN_SCENE_Y,
	//PSST_TERRAIN_SCENE_Z,

	PSST_TERRAIN_SHADOW,	
	//PSST_TERRAIN_POINTLIGHTSHADOW,	
	PSST_TERRAIN_SPOTLIGHTSHADOW,
	PSST_TERRAIN_DEFERRED,
	PSST_TERRAIN_DEPTHNORMAL,

	PSST_TERRAIN_GRASS,

	//PSST_TERRAIN_DEFERRED_X,
	//PSST_TERRAIN_DEFERRED_Y,
	//PSST_TERRAIN_DEFERRED_Z,

	PSST_TERRAIN_DEFERRED_Y_SOFT,
	PSST_TERRAIN_LAYER_EXPORT,

	PSST_TERRAIN_DEFERRED_NORMAL_X,
	PSST_TERRAIN_DEFERRED_NORMAL_Y,
	PSST_TERRAIN_DEFERRED_NORMAL_Z,

	PSST_TERRAIN_DEPTHNORMAL_X,
	PSST_TERRAIN_DEPTHNORMAL_Y,
	PSST_TERRAIN_DEPTHNORMAL_Z,

	PSST_TERRAIN_DEFERRED_X_PARALLAX,
	PSST_TERRAIN_DEFERRED_Y_PARALLAX,
	PSST_TERRAIN_DEFERRED_Z_PARALLAX,

	PSST_TERRAIN_DEPTHNORMAL_X_PARALLAX,
	PSST_TERRAIN_DEPTHNORMAL_Y_PARALLAX,
	PSST_TERRAIN_DEPTHNORMAL_Z_PARALLAX,

	PSST_TERRAIN_NORMAL_EDIT,
	PSST_TERRAIN_EDITPLANE_NORMAL,
	PSST_TERRAIN_EDITMOUSEPOINT_NORMAL,

	PSST_TERRAIN_EDIT_CUBEMAP,
	PSST_TERRAIN_EDIT_CUBEMAPINSIDE,

	PSST_TERRAIN_LOD,
	PSST_TERRAIN_LOD_GRASS,
	PSST_TERRAIN_FAR,

	//PSST_TERRAIN_EFFECT,
	PSST_TERRAIN_REGION,

	PSST_SHADOW_OUTDOOR_GENERATE,
	PSST_SHADOW_OUTDOOR_COMBINE,
	PSST_SHADOW_OUTDOOR_SELFONLY,

	PSST_SHADOW_OUTDOOR_LONGTERMAO,
	PSST_SHADOW_OUTDOOR_TRACE_LONGTERMAO,
	

	PSST_SHADOW_OUTDOOR_LONGTERMAOVOLUME,

	PSST_SHADOW_INDOOR_SSAO,

	PSST_SHADOW_SELF_GENERATE,

	//PSST_SHADOW_INDOOR,
	//PSST_POINTSPOT_SHADOW,

	PSST_SHADOW_OUTDOOR_INDIRECTILLUMINATION_GENERATE,

	/*PSST_RADIANCEVOLUME_LIGHTINJECTION,
	PSST_RADIANCEVOLUME_LIGHTPROPAGATION,
	PSST_RADIANCEVOLUME_INJECTIONOCCLUSION,
	PSST_RADIANCEVOLUME_COLLISIONINFOINJECTIONOCCLUSION,
	PSST_RADIANCEVOLUME_RADIANCEVOLUMERENDER,
	PSST_RADIANCEVOLUME_ADD,*/

	PSST_SHADOW_LIGHTSCENE,
	PSST_SHADOW_LIGHT,
	PSST_SHADOW_LIGHTGEOMETRY,
	PSST_SHADOW_LIGHTGEOMETRY_SCATTER,
	PSST_SHADOW_LIGHTGEOMETRY_BLEND,
	PSST_SHADOW_LIGHTGEOMETRY_GI,

	PSST_SHADOW_OUTDOOR_DYNAMICAO,	

	//PSST_SHADOW_GILIGHTGEOMETRY,
	//PSST_SHADOW_GILIGHTGEOMETRY_NEAR,
	PSST_SHADOW_GILIGHTTILE,	
	PSST_SHADOW_GILIGHTTILE_AMBIENT,
	PSST_SHADOW_GILIGHTTILE_NEAR,	
	PSST_SHADOW_GILIGHTTILE_COLORGENERATE,
	PSST_SHADOW_LIGHTTILE,
	PSST_SCENELIGHT_INDOOR,

	PSST_SHADOW_SCENEENVGENERATE,
	PSST_SHADOW_SCENELIGHTENVGENERATE,
	PSST_SHADOW_SPHERE_SCENEENVGENERATE,

	//PSST_SHADOW_BOUNDBOX,
	//PSST_SHADOW_BOUNDBOX_CHARACTER,
	//PSST_SHADOW_BOUNDBOX_GRASS,

	//PSST_SHADOW_MATERIAL,

	PSST_SHADOW_GIAO_GENERATE,
	PSST_SHADOW_SSAO_GENERATE,

	PSST_SHADOW_SSLS_GENERATE,
	PSST_SHADOW_LIGHTSHAFT_GENERATE,	
	PSST_SHADOW_LIGHTSHAFT_RESULT,
	PSST_SSENV,

	PSST_SHADOW_LIGHTSCATTERING,

	PSST_SHADOW_INJECTRADIANCE,	
	PSST_SHADOW_INJECTRAMBIENTOCCLUSION,
	PSST_SHADOW_PROPAGATERADIANCE,	

	PSST_SHADOW_INDIRECTILLUMINATION,

	PSST_SHADOW_EXPBLUR,

	//PSST_OBJECT_SCENE,

	PSST_OBJECT_SHADOW,
	PSST_OBJECT_VOXEL,
	PSST_OBJECT_SHADOW_BOX,
	PSST_OBJECT_SHADOWSIMPLE,
	PSST_OBJECT_POINTLIGHTSHADOW,
	PSST_OBJECT_SPOTLIGHTSHADOW,
	PSST_OBJECT_DEFER,
	PSST_OBJECT_DEPTHNORMAL,

	PSST_OBJECT_FONT_DEFER,

	PSST_OBJECT_DEFER_BLEND,
	PSST_OBJECT_DEFER_BACKFACE,
	PSST_OBJECT_DEFER_LOD,	
	PSST_OBJECT_DEPTHNORMAL_LOD,
	//PSST_OBJECT_DECAL_SCENE,
	PSST_OBJECT_DECAL_DEFER,
	PSST_OBJECT_DECAL_ROAD_DEFER,
	PSST_OBJECT_DECAL_ROAD_DEPTH,
	PSST_OBJECT_DECAL_RAINPOOL,
	PSST_OBJECT_DECAL_FOWARD,
	PSST_OBJECT_MASS_DECAL_DEFER,

	PSST_OBJECT_EDGE,
	PSST_OBJECT_INDOOR,

	PSST_OBJECT_DECAL_EDIT,
	PSST_OBJECT_DEFER_EDIT,

	//PSST_OBJECT_EDGE,
	PSST_OBJECT_WATER,
	PSST_OBJECT_WATERMASK,

	PSST_OBJECT_SELECT,
	PSST_OBJECT_SELECT_SOLID,
	PSST_OBJECT_SELECT_DIFFUSE,
	PSST_OBJECT_SELECT_EFFECT,

	PSST_OBJECT_GIZMO,
	PSST_LINEVERTEX,

	PSST_OBJECT_NAVIVOXEL,
	PSST_WEATHER_PARTICLE2,
	PSST_FAR_WEATHER_PARTICLE,
	PSST_WEATHER_DROP_PARTICLE,
	PSST_WEATHER_LENSDIRT_PARTICLE,

	//PSST_DECAL_DEFER,
	PSST_DECAL_DEFER_VOLUME,
	PSST_DECAL_CAUSTIC_VOLUME,
	PSST_DECAL_DEFER_VOLUME_EDIT,
	
	PSST_DECAL_LIGHT_VOLUME,

	PSST_CHARACTER_DEFER,
	PSST_CHARACTER_DEFER_CUSTOMIZE_FACE,
	PSST_CHARACTER_DEFER_CUSTOMIZE_EYE,
	PSST_CHARACTER_DEFER_DECAL,
	PSST_CHARACTER_DEFER_DECAL_SOFT,
	PSST_CHARACTER_SHADOW,
	PSST_CHARACTER_SPOTLIGHTSHADOW,
	PSST_CHARACTER_HAIR_FORWARD,
	PSST_CHARACTER_HAIR_DEPTH,
	PSST_CHARACTER_HELM_DEPTH,
	PSST_CHARACTER_EDGE,
	PSST_CHARACTER_EFFECT,
	PSST_CHARACTER_CLOAKING,
	PSST_CHARACTER_WATERMASK,
	PSST_CHARACTER_VELOCITY,

	PSST_CHARACTER_LIGHTAO,

	PSST_SWORD_TRAIL,
	PSST_SWORD_TRAIL_SCREEN,
	PSST_SWORD_TRAIL_MUL,
	PSST_SWORD_TRAIL_DISTORTION,

	PSST_SPEEDTREE6_DEFER,	
	//PSST_SPEEDTREE6_SCENE,
	PSST_SPEEDTREE6_SHADOW,
	PSST_SPEEDTREE6_SPOTLIGHTSHADOW,
	PSST_SPEEDTREE6_GRASS_SHADOW,
	PSST_SPEEDTREE6_BILLBOARD_DEFER,
	//PSST_SPEEDTREE6_BILLBOARD_SCENE,
	PSST_SPEEDTREE6_BILLBOARD_SHADOW,
	PSST_SPEEDTREE6_GRASS_DEFER,	
	PSST_SPEEDTREE6_WEED_DEFER,
	PSST_SPEEDTREE6_PIXELCULLCOPY,

	PSST_CLOUDSCENE,

	PSST_CLOUDIMPOSTOR,
	PSST_CLOUDIMPOSTORUPDATE,
	PSST_CLOUDIMPOSTORRENDER,

	PSST_CLOUDSCENE_FINAL,
	PSST_CLOUDSCENE_CULLDEPTH,
	PSST_CLOUDSHADOW,

	PSST_VOLUMEFOGSCENE,
	PSST_VOLUMEFOGSCENEBLEND,	

	PSST_SCENEREFLECT,
	PSST_SCENESCATTER,

	PSST_DEBUG,

	PSST_BLOOM,	

	PSST_BLUR,
	PSST_BLUR_DIR,
	PSST_BLUR_EDGEPRESERVE_DIR,

	PSST_EDGECOPY,
	PSST_EDGEBLUR_DIR,

	PSST_RENDERSCENE,
	PSST_RENDERSCENE_SSS,
	PSST_RENDERSCENE_LOW,
	PSST_RENDERSCENE_SATELLITESHOT,

	PSST_EFFECT_MESH,
	PSST_EFFECT_MESH_ALPHA,
	PSST_EFFECT_MESH_MULTYKEY,
	PSST_EFFECT_MESH_MULTYKEY_ALPHA,
	PSST_EFFECT_MESH_DEFERRED,
	PSST_EFFECT_MESH_SHADOW,

	PSST_EFFECTTRAILSCENE,

	PSST_EDGEDETECT,

	PSST_COPYTOBACKBUFFER,
	PSST_RENDERTOBACKBUFFER,
	PSST_UPSCALE,

	PSST_AA_EDGEDETECT_LUMA,
	PSST_AA_EDGEDETECT_COLOR,
	PSST_AA_EDGEDETECT_DEPTH,

	PSST_AA_BLENDWEIGHTCALC,
	PSST_AA_NEIGHBORBLEND,

	PSST_AA_FXAA,

	PSST_WEAVE,
	PSST_DEINTERLACE,

	PSST_SMALLCOPY,
	PSST_SMALLCOPYMAX,
	
	PSST_COPYMATERIAL_SAVE,

	PSST_FINALCOMPOSITE,

	PSST_HDR_DOWNSCALE_LUMINACE,
	PSST_HDR_DOWNSCALE_3X3,	

	PSST_HDR_BRIGHTPASS,	
	PSST_HDR_ACCMULATE,
	PSST_HDR_BRIGHTPASS_STAR,	

	PSST_HDR_STAR,
	PSST_HDR_MERGE,

	PSST_HDR_GHOST,	

	PSST_GRADATION,

	PSST_HDR_GATHERENV,

	PSST_GENERATE_SCENEDEPTH,
	//PSST_GENERATE_SCENEDIFFUSENORMAL,

	PSST_GENERATE_SMALLNORMAL,

	//PSST_GENERATE_SMALLDEPTH,

	//PSST_COPY,

	PSST_MOTIONBLUR,

	PSST_BOUNDBOX,

	PSST_GRID,

	PSST_OCCLUSIONCULL,

	PSST_UNDERWATERFOG, 
	//PSST_WETBYRAIN, 

	PSST_DUPLICATOR_OVR, 

	PSST_AI_DEBUGINFO, 
	PSST_REGIONINFO_DEBUG,
	PSST_CUSTOMINFO_DEBUG,
	PSST_VILLAGESEIGEINFO_DEBUG,

	PSST_VOXEL_DEBUG,

	PSST_FXAA,
	PSST_TAA,

	PSST_CACHEREPROJECTION,

	PSST_SOFTALPHATEST,

	PSST_POINTBLUR,
	PSST_CHROMATIC_BLUR,

	PSST_DOF,
	PSST_BOKEH,

	PSST_UI_BASE,

	PSST_VOLUMELINE,
	PSST_VOLUMELINE_LINKED,
	PSST_VOLUMELINE_DIR,

	PSST_FADE_SCREEN,
	PSST_INGAME_UI,

	/*PSST_BICUBIC,
	PSST_EFFECT_COMPOSITE,*/

	PSST_BLUR_BASE_UISCENE,
	PSST_BLUR_BASE_UISCENE_COMPOSITE,

	PSST_OBJECT_UISCENE,

	PSST_OBJECT_MINI,
	PSST_OBJECT_MINI_SHADOW,
	PSST_OBJECT_MINIWIRE,	

	PSST_OBJECT_MINI_BOX,
	PSST_OBJECT_MINI_POLY,
	
	PSST_TERRAIN_WORLDMAP,
	PSST_TERRAIN_WORLDMAP_GRASS,
	PSST_TERRAIN_WORLDMAP_CLOUD,
	PSST_TERRAIN_WORLDMAP_SHADOW,

	PSST_HOUSINGINFO,

	PSST_EFFECT_LINE,	
	//PSST_EFFECT_MESH_WIRE,	
	PSST_EFFECT_POPCORN_PARTICLE,
	PSST_EFFECT_POPCORN_PARTICLE_DEBUG,
	PSST_EFFECT_POPCORN_PARTICLE_DISTORTION,
	//PSST_EFFECT_POPCORN_PARTICLE_INSTANCING,
	//PSST_EFFECT_HHMESH,


	PSST_DUNGEON_BOUNDARY,
	PSST_DUNGEON_BOUNDARY_EDIT,
	PSST_RENDERUI_NORMAL,

	PSST_AALINE,
	PSST_AALINE_NODEPTH,
	PSST_AALINE_WORLD,
	PSST_AACIRCLE,

	PSST_DYNAMICEFFECT_MESH_MULTYKEY,
	PSST_DYNAMICEFFECT_MESH_MULTYKEY_ALPHA,
	PSST_DYNAMICEFFECT_PARTICLE_TEXTURE,

	PSST_PAEFFECT_SCENE,
	PSST_PAEFFECT_SCENE_DEBUG,
	PSST_PAEFFECT_SCENE_DISTORTION,
	PSST_PAEFFECT_INSTANCING,
	PSST_PAEFFECT_INSTANCING_DEBUG,
	PSST_PAEFFECT_INSTANCING_DISTORTION,
	PSST_PAEFFECT_SCENE_UI,
	PSST_PAEFFECT_SCENE_TEST,
	PSST_PAEFFECT_SCENE_PREVIEW,
	PSST_PAEFFECT_MESHSCENE,
	PSST_PAEFFECT_MESHSCENE_DEBUG,
	PSST_PAEFFECT_MESHSCENE_DISTORTION,
	PSST_PAEFFECT_MESHSCENE_UI,
	PSST_PAEFFECT_MESHSCENE_UI_DEBUG,
	PSST_PAEFFECT_MESHSCENE_TEST,
	PSST_PAEFFECT_RIBBON,

	PSST_CLEAR,

	PSST_CS_TILINGFORWARD,

	PSST_MAX
};
