enum PASceneConstValue
{
	PSCV_SUNCOLOR,

	PSCV_SUNGLARECOLOR,

	PSSV_SUNSCATTERCOLOR,

	PSCV_AMBIENTCOLOR_UP,
	PSCV_AMBIENTCOLOR_DOWN,
	
	PSCV_AMBIENTOCCLUSIONCOLOR,
	PSCV_AMBIENTOCCLUSIONCOLOR_DEEP,

	PSCV_FOGCOLOR0,	// array
	PSCV_FOGCOLOR1,
	PSCV_FOGCOLOR2,

	PSCV_SKYBASECOLOR,
	PSCV_EXTINCTIONCOLOR,

	PSCV_HORIZON0COLOR,
	PSCV_HORIZON1COLOR,
	PSCV_REIGHCOLOR,

	PSCV_SCATTERDIATANCEFALLOFF,
	PSCV_MIEDIATANCEFALLOFF,
	PSCV_MIEHEIGHT,
	PSCV_REIGHDISTANCEFALLOFF,
	PSCV_SUNSCATTEREXP,
	PSCV_HORIZONEXP0,
	PSCV_HORIZONEXP1,
	PSCV_SUNEXP,
	PSCV_SUNGLAREEXP,

	PSCV_CLOUDLAYER0,	// Alpha
	PSCV_CLOUDLAYER1,	// Point Size
	PSCV_CLOUDLAYER2,	// XZ Size

	PSCV_GRAYSCALE,
	PSCV_OVERLAY,
	PSCV_CONTRAST_POST,
	PSCV_SATURATION,
	PSCV_BRIGHTNESS,
	PSCV_COLORBALANCER,
	PSCV_COLORBALANCEG,
	PSCV_COLORBALANCEB,

	PSCV_ENVINTENSITY,

	PSCV_SKINAMBIENTCOLOR,
	PSCV_HAIRAMBIENTCOLOR,

	PSCV_EFFECT_AMBIENTCOLOR,
	PSCV_EFFECT_AMBIENTCOLOR_ALPHA,
	PSCV_EFFECT_AMBIENTCOLOR_HIT,
	PSCV_EFFECT_AMBIENTCOLOR_HIT_ALPHA,
	
	PSCV_CLOUDLAYER3,	// Y Size
	PSCV_CLOUDLAYER4,	// Shadow Layer
	PSCV_CLOUDLAYER5,	// Height
	PSCV_CLOUDLAYER6,	// Sun Clip
	PSCV_CLOUDLAYER7,	// CloudLight
	PSCV_CLOUDLAYER8,	// Ambient Light
	PSCV_CLOUDLAYER9,	// Shadow

	PSCV_CLOUDLAYER10,	// Sky
	PSCV_CLOUDLAYER11,	// Sky
	PSCV_CLOUDLAYER12,	// Sky

	PSCV_CHARACTERLIGHTRATE,
	PSCV_CHARACTERLIGHTRATE2,

	PSCV_LIGHTATTACHRATE,
	PSCV_STARRATE,
	PSCV_WEATHERAPPLY,

	PSCV_MOONY,
	PSCV_MOONX,
	PSCV_INTENSITYRATE,
	
	PSCV_LONGTERMAOHEIGHT,
	PSCV_LONGTERM_TERRAIN_HEIGHT,
	
	PSCV_MOONRATE,		
	PSCV_TEST_WIND_STRENGTH,

	//////////////////////////////////////
	PSCV_SEAWAVE_GERSTNER_AMPLITUDE,
	PSCV_SEAWAVE_GERSTNER_LENGTH,
	PSCV_SEAWAVE_GERSTNER_STEEPNESS,
	PSCV_SEAWAVE_PARTICLE_HEIGHT,
	PSCV_SEAWAVE_FOAM_HEIGHT,
	////////////////////////////////////

	PSCV_RAINPOOL,	
	PSCV_SUNY,
	PSCV_SUNX,

	PSCV_SEAHEIGHT,
	PSCV_SEAWAVE_HEIGHT,
	PSCV_SEAWAVE_FREQUENCY2,	

	PSCV_SEABASECOLOR,
	PSCV_SEANEARCOLOR,
	PSCV_SEAFARCOLOR,

	PSCV_TEST_RAIN_AMOUNT,
	PSCV_TEST_HUMIDITY,
	PSCV_TEST_AIR_TEMPERATURE,

	PSCV_DOF_FRINGE,
	PSCV_DOF_THRESHOLD,
	PSCV_DOF_GAIN,
	PSCV_DOF_FOCALPLANE,
	PSCV_DOF_NEARSTART,
	PSCV_DOF_NEAREND,
	PSCV_DOF_FARSTART,
	PSCV_DOF_FAREND,
	PSCV_DOF_BLUR,	

	PSCV_CLOUDCOLOR,

	PSCV_MAX
};
