enum PAScenePrimitiveMeshInfoType
{	
	SPMIT_FULLSCENEQUAD,
	SPMIT_OBJECT,
	SPMIT_OBJECT_INSTANCING,

	SPMIT_SPEEDTREE6,
	SPMIT_SPEEDTREE6_SIMPLE,
	SPMIT_SPEEDTREE6_BILLBOARD,
	SPMIT_SPEEDTREE_BRANCH,
	SPMIT_SPEEDTREE_FROND,
	SPMIT_SPEEDTREE_LEAFMESH,
	SPMIT_SPEEDTREE_LEAFCARD,
	SPMIT_SPEEDTREE_GRASS,	
	SPMIT_SPEEDTREE_BILLBOARD,	

	SPMIT_CHARACTER,
	SPMIT_CHARACTER_HALF,
	SPMIT_CHARACTER_MORPH,		// FACE MORPHING
	SPMIT_CHARACTER_LIGHT_AO,
	SPMIT_SWORDTRAIL,

	//SPMIT_CHARACTER_BONEPALETTE,

	SPMIT_TERRAIN,
	SPMIT_TERRAIN_INSTANCING,

	SPMIT_CLOUDLAYER,
	SPMIT_SEAGRID,
	SPMIT_SEAHEIGHTCALC,
	SPMIT_VOLUMEWATER,

	SPMIT_GIINFO,
	SPMIT_AOINFO,

	SPMIT_BOX,
	
	SPMIT_POSITION3_INSTANCING,
	SPMIT_POSITION4,
	SPMIT_POSITION3,

	SPMIT_POSITION_WORLD,
	SPMIT_DECAL_VOLUME,

	SPMIT_GRID,

	SPMIT_VOXEL_NAVI_INSTANCING,
	SPMIT_WEATHER_PARTICLE,
	SPMIT_WEATHER_PARTICLE_INSTANCING,

	SPMIT_VOLUMEFOG,
	SPMIT_CLOUD,
	SPMIT_CLOUD_IMPOSTOR,
	SPMIT_LIGHTCOLLISIONINFO,

	SPMIT_DOF_BOKEH,

	SPMIT_GITEX,
	SPMIT_TRAIL,

	SPMIT_VOLUMELINE,

	SPMIT_EFFECT_MESH,

	SPMIT_EFFECT_LINE,

	SPMIT_EFFECT_MESH_MULTIKEY,

	SPMIT_EFFECT_HH_PARTICLE,
	SPMIT_EFFECT_HH_MESH,

	SPMIT_EFFECT_PARTICLE3,
	SPMIT_EFFECT_PARTICLE3_INSTANCING,
	SPMIT_EFFECT_PARTICLE3_MESH,

	SPMIT_EFFECT_RIBBON,

	SPMIT_AALINE,
	SPMIT_AACIRCLE,

	SPMIT_BOUNDARY,

	SPMIT_FLOAT4,
	SPMIT_UI_BASE,
	SPMIT_UI_FADESCREEN,

	SPMIT_MAX,
};
