enum PASceneRenderTargetType
{	
	SRTT_HDRTARGET,		
	//SRTT_HDRTARGET_SSS,		
	SRTT_BACKBUFFER,
	SRTT_BACKBUFFER_FULLSIZE,

	//SRTT_DOF_COMPOSITE,
	SRTT_TEMPCOPY_SMALL_MIPMAP,

	//SRTT_SCENEDEPTHSTENCIL,		
	//SRTT_SMALL_SCENEDEPTHSTENCIL,

	//SRTT_FINALRESULT0,
	//SRTT_FINALRESULT1,
	//SRTT_FINALRESULT_REPROJECT,		
	
	//SRTT_SKY,
	SRTT_SKY_SMALL,
	SRTT_NORMAL,
	SRTT_NORMAL_SMALL,

	//SRTT_NORMAL_VERTEX,

	//SRTT_DEPTHBACKUP,
	//SRTT_16X4F_TEMP_1,

	//SRTT_DIFFUSE_NORMAL,	
	//SRTT_DIFFUSE_NORMAL_SRC,	

	SRTT_DIFFUSE,	
	//SRTT_DIFFUSE2,	
	SRTT_TEMPCOPY,	
	SRTT_TEMPCOPY2,
	//SRTT_VELOCITY,

	//SRTT_CACHEREPROJECTION,

	SRTT_SKY_FARCLOUDDENSITY,
	SRTT_SKY_FARCLOUDBLUR,

	//SRTT_DEPTH_LOD,
	//SRTT_DIFFUSE_LOD,

	SRTT_DEPTH,
	SRTT_DEPTH_SMALL,
	SRTT_DEPTH_SMALL_RESIZE,
	SRTT_DEPTH_SMALL_RESIZE_INDOORSCATTER,
	SRTT_DEPTH_SKIN,
	SRTT_DEPTH_SMALL_SKIN,


	//SRTT_OCCLUSION_DEPTH,
	//SRTT_OCCLUSION,
	//SRTT_OCCLUSION_RESULT,
	//SRTT_OCCLUSION_RESULT_RAWDATA,

	SRTT_PROBESCENE_ENVMAP,
	SRTT_PROBESCENE_SPHEREMAP,

	//SRTT_DEPTH_ENVMAP,
	//SRTT_DEPTH_ENVMAP_RAW,
	//SRTT_NORMAL_ENVMAP,
	//SRTT_DIFFUSE_ENVMAP,
	//SRTT_MATERIAL_ENVMAP,
	//SRTT_DIFFUSE_NORMAL_ENVMAP,

	//SRTT_SHADOWMAP,	
	SRTT_OUTDOORSHADOWMAP0,
	SRTT_OUTDOORSHADOWMAP1,
	//SRTT_OUTDOORSHADOWMAP2_DEPTH,
	SRTT_OUTDOORSHADOWMAP2,	
	SRTT_OUTDOORSHADOWMAP2_NORMAL,
	SRTT_OUTDOORSHADOWMAP2_DIFFUSE,
	SRTT_OUTDOORSHADOWMAP3,		

	SRTT_OUTDOORSHADOWMAP_DYNAMIC0,
	SRTT_OUTDOORSHADOWMAP_DYNAMIC1,	
	SRTT_OUTDOORSHADOWMAP_SELF0,	// Self
	SRTT_OUTDOORSHADOWMAP_SELF1,	// SelfHair

	SRTT_OUTDOORSHADOWMAPAO,	
	SRTT_OUTDOORSHADOWMAPAO_NEAR,	
	//SRTT_OUTDOORSHADOWMAPAO_NEAR_DYNAMIC,	

	//SRTT_OUTDOORSHADOWMAP0_DYNAMIC,
	//SRTT_OUTDOORSHADOWMAP1_DYNAMIC,	

	//SRTT_OUTDOOR_HEIGHTMAP,

	SRTT_GILIGHTINDEX_POSITION,
	SRTT_GILIGHTINDEX_NORMAL,
	SRTT_GILIGHTINDEX_COLOR,

	//SRTT_GILIGHTINDEX_POSITION_NEAR,
	//SRTT_GILIGHTINDEX_NORMAL_NEAR,
	//SRTT_GILIGHTINDEX_COLOR_NEAR,

	/*SRTT_OUTDOORHEIGHTMAP_SS,
	SRTT_OUTDOORHEIGHTMAP_LOD0,
	SRTT_OUTDOORHEIGHTMAP_LOD0_SWAP,
	SRTT_OUTDOORHEIGHTMAP_LOD1,
	SRTT_OUTDOORHEIGHTMAP_LOD1_SWAP,
	SRTT_OUTDOORHEIGHTMAP_LOD2,
	SRTT_OUTDOORHEIGHTMAP_LOD2_SWAP,
	SRTT_OUTDOORHEIGHTMAP,
	SRTT_OUTDOORHEIGHTMAP_SWAP,*/

	//SRTT_DYNAMICENVMAP0,
	//SRTT_DYNAMICENVMAP1,
	//SRTT_DYNAMICENVMAP2,

	//SRTT_TONEMAPENVMAP0,
	//SRTT_TONEMAPENVMAP1,
	//SRTT_TONEMAPENVMAP2,

	//SRTT_POINTLIGHTSHADOWMAP,

	//SRTT_POINTSPOT_SHADOWRESULT,

	//SRTT_SPOTLIGHT_DYNAMICSHADOWMAP,
	SRTT_SPOTLIGHT_DYNAMICSHADOWMAP0,
	SRTT_SPOTLIGHT_DYNAMICSHADOWMAP1,
	SRTT_SPOTLIGHT_DYNAMICSHADOWMAP2,
	SRTT_SPOTLIGHT_DYNAMICSHADOWMAP_INSTANCELIGHT,	// Lantern
	SRTT_SPOTLIGHTSHADOWMAP_INSTANCELIGHT_ATLAS,
	SRTT_SPOTLIGHTSHADOWMAP0,
	SRTT_SPOTLIGHTSHADOWMAP1,
	SRTT_SPOTLIGHTSHADOWMAP2,
	SRTT_SPOTLIGHTSHADOWMAP3,
	SRTT_SPOTLIGHTSHADOWMAP4,
	SRTT_SPOTLIGHTSHADOWMAP5,
	SRTT_SPOTLIGHTSHADOWMAP6,
	SRTT_SPOTLIGHTSHADOWMAP7,
	
	//SRTT_SCENESHADOWRESULT,
	SRTT_SCENESHADOWRESULT_SMALL,	// AO ��
	//SRTT_SCENEINDOORSHADOWRESULT,
	//SRTT_SCENESHADOWRESULT_PRE,

	//SRTT_TEMPCOPY_SMALL,

	//SRTT_SCENELIGHTRESULT_MULTIPLY_0,
	//SRTT_SCENELIGHTRESULT_MULTIPLY_1,
	//SRTT_SCENELIGHTRESULT_MULTIPLY_2,

	SRTT_SCENEVOXEL,
	SRTT_SCENEVOXEL_DUMMY,

	SRTT_SCENESHADOWRESULT_PLUS_AXIS,
	SRTT_SCENESHADOWRESULT_MINUS_AXIS,

	SRTT_SCENE_INDOOR_PLUS,
	SRTT_SCENE_INDOOR_MINUS,

	SRTT_SCENEILRESULT,
	//SRTT_SCENEILRESULT_PRE,

	SRTT_SCENEILRESULT_PLUS_AXIS,
	SRTT_SCENEILRESULT_MINUS_AXIS,
	SRTT_SCENEILRESULT_EXTRA_AXIS,

	SRTT_SCENE_REFLECT_RESULT,
	SRTT_SCENE_REFLECT_COPY,

	//SRTT_SCENEMATERIALRESULT,
	//SRTT_SCENEMATERIALRESULT2,

	//SRTT_SCENELIGHTRESULT,

	//SRTT_SCENELIGHTRESULT_MULTIPLY,
	//SRTT_SCENELIGHTRESULT_ADD,

	SRTT_SCENELIGHTSCATTERINGRESULT,
	//SRTT_SCENESCATTERINGRESULT,

	//SRTT_SCENELIGHTRESULT_ENVMAP,
	//SRTT_SCENELIGHTSCATTERINGRESULT_ENVMAP,

	//SRTT_SCENEREFLECT,
	
	SRTT_SSLIGHTSHAFTRESULT,	
	SRTT_SCENESCATTERRESULT,
	//SRTT_LIGHTSHAFTRESULT_BLURTEMP,	
	//SRTT_RANDOM,

	//SRT_DOF_SMALL_BLUR,
	SRTT_DUPLICATOR_OVR,	

	SRT_HDR_TONEMAP_0,
	SRT_HDR_TONEMAP_1,
	SRT_HDR_TONEMAP_2,
	SRT_HDR_TONEMAP_3,
	SRT_HDR_TONEMAP_4,

	SRT_HDR_BLOOM_ACCMUALTE,

	SRT_HDR_BLOOM,
	SRT_HDR_BLOOM_BLURTEMP,

	SRT_HDR_BLOOM_0,
	SRT_HDR_BLOOM_BLURTEMP_0,

	SRT_HDR_BLOOM_1,
	SRT_HDR_BLOOM_BLURTEMP_1,

	SRT_HDR_BLOOM_2,
	SRT_HDR_BLOOM_BLURTEMP_2,

	SRT_HDR_BLOOM_3,
	SRT_HDR_BLOOM_BLURTEMP_3,

	SRT_HDR_BLOOM_4,
	SRT_HDR_BLOOM_BLURTEMP_4,

	SRT_STAR_0,
	SRT_STAR_1,
	SRT_STAR_2,
	SRT_STAR_3,

	SRT_STAR_4,
	SRT_STAR_5,
	SRT_STAR_6,
	SRT_STAR_7,

	SRT_STAR_8,
	SRT_STAR_9,
	SRT_STAR_10,
	SRT_STAR_11,

	SRT_GHOST_0,
	SRT_GHOST_1,

	//SRTT_INSCATTER,
	//SRTT_IRRADIANCE,
	//SRTT_TRANSMITTANCE,	
	//SRTT_NOISE,
	//SRTT_NOISE_NORMAL,
	//SRTT_ENV,
	//SRTT_MLAA_AIRES,

	//SRTT_ILSHADOWMAP,

	//SRTT_FILMSIMULATION_LUT,

	//SRTT_FILMSIMULATION_BOKEH_1,

	//SRTT_ENVTEST,
	//SRTT_ENVTEST_IRRADIANCE,
	//SRTT_ENVTEST_ROUGHSPEC,

	//SRTT_ANISTROPIC,

	//SRTT_IRRADIANCEVOLUME_PLUS,
	//SRTT_IRRADIANCEVOLUME_MINUS,

	SRTT_CHARACTERMATRIXPALETTE,
	SRTT_CHARACTERMATRIXPALETTE2,	// Buffer Test

	SRTT_FORWARDPLUS_LIGHTCENTERRADIUS,
	SRTT_FORWARDPLUS_LIGHTCOLOR,
	SRTT_FORWARDPLUS_DEBUG,
	SRTT_FORWARDPLUS_LIGHTINDEX_UAV,
	SRTT_FORWARDPLUS_LIGHTINDEX_UAV_READ,

	//SRTT_LIGHTINDEXED_0, 
	//SRTT_LIGHTINDEXED_1, 
	//SRTT_LIGHTINDEXED_2, 
	//SRTT_LIGHTINDEXED_INFO,
	/*SRTT_LIGHTINDEXED_INFO_POSITION,
	SRTT_LIGHTINDEXED_INFO_COLOR,
	SRTT_LIGHTINDEXED_INFO_VOLUMEINFO,
	SRTT_LIGHTINDEXED_INFO_NORMAL,*/

	SRTT_CHARACTER_LIGHTAO,	

	SRTT_SEA_HEIGHT_OFFSET,

	SRTT_CLOUD_SCENE,	
	SRTT_CLOUD_LIGHT,
	SRTT_CLOUD_SHADOW,

	SRTT_CLOUD_IMPOSTOR_DEPTH,
	SRTT_CLOUD_IMPOSTOR0,
	SRTT_CLOUD_IMPOSTOR1,
	SRTT_CLOUD_IMPOSTOR2,
	SRTT_CLOUD_IMPOSTOR3,
	SRTT_CLOUD_IMPOSTOR4,
	SRTT_CLOUD_IMPOSTOR5,
	SRTT_CLOUD_IMPOSTOR6,
	SRTT_CLOUD_IMPOSTOR7,

	SRTT_CHARACTER_HELM_DEPTH,	// ���ڰ� �Ӹ��� �Ĺ����°� ��ȭ�ϱ� ����...
	SRTT_CHARACTER_HELM_DEPTH_SMALL,
	//SRTT_WORLDMAP,
	//SRTT_WORLDMAP_DEPTH,
	SRTT_MAX,
};
