enum PASceneCullMode
{
	PASCM_VIEW = 0,
	PASCM_SHADOW0,
	PASCM_SHADOW1,
	PASCM_SHADOW2,
	PASCM_SHADOW3,
	
	PASCM_SHADOWAO,
	//PASCM_SHADOW_DYNAMICNEAR = PASCM_SHADOWAO,	// DYNAMICNEAR : character only

	PASCM_POINTLIGHT,

	PASCM_MAX
};
