enum PATextureMethod
{
	// resource
	PATM_2D, 
	PATM_3D,
	PATM_ENV,
	PATM_2D_UI,
	PATM_2D_UI_XXX,	// DDS �� �ٸ� ���Ͽ�

	// raw_float
	PATM_32F_RAW,
	PATM_2D_DYNAMIC, // ���� : ����Ÿ�ٺ����
	PATM_32F_DYNAMIC,
	PATM_DYNAMIC,	 // (dongwook): ��Ű�� �ؽ��ĸ� ����� ���� �߰���.
	PATM_BUFFER_DYNAMIC_DX11,		// PATM_DYNAMIC Buffer ����
	PATM_BUFFER_DYNAMIC_DX11_READ,	// PATM_BUFFER_DYNAMIC_DX11 debugging��
	PATM_R16_UNORDER_READ,			// PATM_R16_UNORDER ����Ÿ�� debugging��
	PATM_DYNAMIC_16X4F,
	PATM_2D_DYNAMIC_UI,
	PATM_2D_DEFAULT_MIPMAP,
	PATM_BUFFER_DEFAULT_DX11VERTEX,

	// raw_uchar
	PATM_8X_RAW,
	PATM_8X_RAW_DYNAMIC,
	PATM_16F_RAW,
	PATM_L16_RAW_DYNAMIC,

	// depthtarget
	PATM_DF24,
	PATM_DF24_SRV,	// Shader Resource View Only
	PATM_D248S,

	// rendertarget
	PATM_A2R10G10B10,
	PATM_CUBE,
	PATM_32F_DEPTH,
	PATM_32X2F_DEPTH,
	PATM_32F,
	PATM_16F,
	PATM_16F_DEPTH,
	PATM_16X2F,
	PATM_DEPTHMAP_32X1F,
	PATM_32X2F,
	PATM_A8R8G8B8,
	PATM_A8R8G8B8_CUBE,		// 20111214, added
	PATM_A8R8G8B8_MIPMAP,
	PATM_A16R16G16B16,
	PATM_A16R16G16B16_DEPTH,
	PATM_A1R5G5B5,	
	PATM_L16,

	PATM_R8_3D_UNORDER,

	PATM_R16_UNORDER,

	PATM_FORCEWORD	= 0xffffffff
};
