enum PAUIMB_TYPE
{
	PAUIMB_TYPE_NONE,
	PAUIMB_TYPE_FREE,
	PAUIMB_TYPE_APPLY,
	PAUIMB_TYPE_CANCEL,
	PAUIMB_TYPE_APPLYCANCEL,
	PAUIMB_TYPE_YESNO,
	PAUIMB_TYPE_APPLYCANCELIGNORE,
	PAUIMB_TYPE_YESNOCANCEL,
};
