enum PAUI_ANIM_ADVANCE_TYPE
{
	PAUI_ANIM_ADVANCE_LINEAR = 0,
	PAUI_ANIM_ADVANCE_LINEAR_2,
	PAUI_ANIM_ADVANCE_SQUARE,
	PAUI_ANIM_ADVANCE_SIN_HALF_PI,
	PAUI_ANIM_ADVANCE_SIN_PI,
	PAUI_ANIM_ADVANCE_COS_HALF_PI,
};
