enum PAVertexElement
{
	//todo : PAVE_POSITION3_INDEX0�� ����??
	PAVE_POSITION3,
	PAVE_POSITION3_INDEX1,
	PAVE_POSITION4,
	PAVE_POSITION4_HALF,

	// Texture #compent count _ $textureIndex
	PAVE_TEXTURE2_INDEX0_HALF,
	PAVE_TEXTURE4_INDEX0_HALF,

	PAVE_TEXTURE2_INDEX1_HALF,
	PAVE_TEXTURE4_INDEX1_HALF,

	PAVE_TEXTURE2_INDEX2_HALF,
	PAVE_TEXTURE4_INDEX2_HALF,

	PAVE_TEXTURE2_INDEX3_HALF,
	PAVE_TEXTURE4_INDEX3_HALF,

	PAVE_TEXTURE2_INDEX4_HALF,
	PAVE_TEXTURE4_INDEX4_HALF,

	PAVE_TEXTURE2_INDEX5_HALF,
	PAVE_TEXTURE4_INDEX5_HALF,

	PAVE_TEXTURE2_INDEX6_HALF,
	PAVE_TEXTURE4_INDEX6_HALF,

	PAVE_TEXTURE2_INDEX7_HALF,
	PAVE_TEXTURE4_INDEX7_HALF,

	PAVE_TEXTURE2_INDEX8_HALF,
	PAVE_TEXTURE4_INDEX8_HALF,

	PAVE_TEXTURE2_INDEX9_HALF,
	PAVE_TEXTURE4_INDEX9_HALF,

	PAVE_TEXTURE2_INDEX10_HALF,
	PAVE_TEXTURE4_INDEX10_HALF,

	PAVE_TEXTURE2_INDEX11_HALF,
	PAVE_TEXTURE4_INDEX11_HALF,

	PAVE_TEXTURE2_INDEX12_HALF,
	PAVE_TEXTURE4_INDEX12_HALF,

	PAVE_TEXTURE2_INDEX13_HALF,
	PAVE_TEXTURE4_INDEX13_HALF,

	PAVE_TEXTURE2_INDEX14_HALF,
	PAVE_TEXTURE4_INDEX14_HALF,

	PAVE_TEXTURE2_INDEX15_HALF,
	PAVE_TEXTURE4_INDEX15_HALF,	

	// Texture #compent count _ $textureIndex
	PAVE_TEXTURE1_INDEX0,
	PAVE_TEXTURE2_INDEX0,
	PAVE_TEXTURE3_INDEX0,
	PAVE_TEXTURE4_INDEX0,

	PAVE_TEXTURE1_INDEX1,
	PAVE_TEXTURE2_INDEX1,
	PAVE_TEXTURE3_INDEX1,
	PAVE_TEXTURE4_INDEX1,

	PAVE_TEXTURE1_INDEX2,
	PAVE_TEXTURE2_INDEX2,
	PAVE_TEXTURE3_INDEX2,
	PAVE_TEXTURE4_INDEX2,

	PAVE_TEXTURE1_INDEX3,
	PAVE_TEXTURE2_INDEX3,
	PAVE_TEXTURE3_INDEX3,
	PAVE_TEXTURE4_INDEX3,

	PAVE_TEXTURE1_INDEX4,
	PAVE_TEXTURE2_INDEX4,
	PAVE_TEXTURE3_INDEX4,
	PAVE_TEXTURE4_INDEX4,

	PAVE_TEXTURE1_INDEX5,
	PAVE_TEXTURE2_INDEX5,
	PAVE_TEXTURE3_INDEX5,
	PAVE_TEXTURE4_INDEX5,

	PAVE_TEXTURE1_INDEX6,
	PAVE_TEXTURE2_INDEX6,
	PAVE_TEXTURE3_INDEX6,
	PAVE_TEXTURE4_INDEX6,

	PAVE_TEXTURE1_INDEX7,
	PAVE_TEXTURE2_INDEX7,
	PAVE_TEXTURE3_INDEX7,
	PAVE_TEXTURE4_INDEX7,

	PAVE_TEXTURE1_INDEX8,
	PAVE_TEXTURE2_INDEX8,
	PAVE_TEXTURE3_INDEX8,
	PAVE_TEXTURE4_INDEX8,

	PAVE_TEXTURE1_INDEX9,
	PAVE_TEXTURE2_INDEX9,
	PAVE_TEXTURE3_INDEX9,
	PAVE_TEXTURE4_INDEX9,

	PAVE_TEXTURE1_INDEX10,
	PAVE_TEXTURE2_INDEX10,
	PAVE_TEXTURE3_INDEX10,
	PAVE_TEXTURE4_INDEX10,

	PAVE_TEXTURE1_INDEX11,
	PAVE_TEXTURE2_INDEX11,
	PAVE_TEXTURE3_INDEX11,
	PAVE_TEXTURE4_INDEX11,

	PAVE_TEXTURE1_INDEX12,
	PAVE_TEXTURE2_INDEX12,
	PAVE_TEXTURE3_INDEX12,
	PAVE_TEXTURE4_INDEX12,

	PAVE_TEXTURE1_INDEX13,
	PAVE_TEXTURE2_INDEX13,
	PAVE_TEXTURE3_INDEX13,
	PAVE_TEXTURE4_INDEX13,

	PAVE_TEXTURE1_INDEX14,
	PAVE_TEXTURE2_INDEX14,
	PAVE_TEXTURE3_INDEX14,
	PAVE_TEXTURE4_INDEX14,

	PAVE_TEXTURE1_INDEX15,
	PAVE_TEXTURE2_INDEX15,
	PAVE_TEXTURE3_INDEX15,
	PAVE_TEXTURE4_INDEX15,	

	PAVE_NORMAL,
	PAVE_TANGENT,
	PAVE_BINORMAL,

	PAVE_NORMALDWORD,
	PAVE_TANGENTDWORD,
	PAVE_BINORMALDWORD,

	PAVE_TANGENTS_4BYTES,

	PAVE_TANGENT_VECTOR4,

	PAVE_COLOR_0,
	PAVE_COLOR_1,
	PAVE_COLOR_2,
	PAVE_COLOR_3,
	PAVE_COLOR_4,
	PAVE_COLOR_5,

	PAVE_BLENDINDICE,
	PAVE_BLENDWEIGHT,
	PAVE_BLENDWEIGHTDWORD,
	
	PAVE_MORPH_POSITION3_INDEX1,
	PAVE_MORPH_TANGENTS_4BYTES_INDEX1,

	// ������ʹ� Instancing ����Ÿ��
	PAVE_INSTANCINGINDEX,
	PAVE_INSTANCINGINDEX2,

	PAVE_INSTANCING_TEXTURE2_INDEX0,

	PAVE_INSTANCING_TEXTURE2_INDEX0_HALF,
	PAVE_INSTANCING_TEXTURE4_INDEX0_HALF,
	PAVE_INSTANCING_TEXTURE2_INDEX1_HALF,
	PAVE_INSTANCING_TEXTURE4_INDEX1_HALF,
	PAVE_INSTANCING_TEXTURE2_INDEX2_HALF,
	PAVE_INSTANCING_TEXTURE4_INDEX2_HALF,
	PAVE_INSTANCING_TEXTURE2_INDEX3_HALF,
	PAVE_INSTANCING_TEXTURE4_INDEX3_HALF,
	PAVE_INSTANCING_TEXTURE2_INDEX4_HALF,
	PAVE_INSTANCING_TEXTURE4_INDEX4_HALF,

	PAVE_INSTANCING_TEXTURE4_INDEX0,
	PAVE_INSTANCING_TEXTURE4_INDEX1,
	PAVE_INSTANCING_TEXTURE4_INDEX2,
	PAVE_INSTANCING_TEXTURE4_INDEX3,
	PAVE_INSTANCING_TEXTURE4_INDEX4,
	PAVE_INSTANCING_TEXTURE4_INDEX5,
	PAVE_INSTANCING_TEXTURE4_INDEX6,
	PAVE_INSTANCING_TEXTURE4_INDEX7,

	PAVE_INSTANCING2_TEXTURE4_INDEX0, //TEXTCOORD2���� �����ϴ� �ν��Ͻ� ����
	PAVE_INSTANCING2_TEXTURE4_INDEX1,
	PAVE_INSTANCING2_TEXTURE4_INDEX2,
	PAVE_INSTANCING2_TEXTURE4_INDEX3,
	PAVE_INSTANCING2_TEXTURE4_INDEX4,
	PAVE_INSTANCING2_TEXTURE4_INDEX5,
	PAVE_INSTANCING2_TEXTURE4_INDEX6,
	PAVE_INSTANCING2_TEXTURE4_INDEX7,
	PAVE_INSTANCING2_TEXTURE4_INDEX8,
	PAVE_INSTANCING2_TEXTURE4_INDEX9,
	PAVE_INSTANCING2_TEXTURE4_INDEX10,
	PAVE_INSTANCING2_TEXTURE4_INDEX11,
	PAVE_INSTANCING2_TEXTURE4_INDEX12,

	PAVE_INSTANCING_BLENDWEIGHT_INDEX0,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX1,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX2,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX3,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX4,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX5,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX6,
	PAVE_INSTANCING_BLENDWEIGHT_INDEX7,
	PAVE_INSTANCING_BLENDINDICES_INDEX0,
	PAVE_INSTANCING_BLENDINDICES_INDEX1,
	PAVE_INSTANCING_BLENDINDICES_INDEX2,
	PAVE_INSTANCING_BLENDINDICES_INDEX3,
	PAVE_INSTANCING_BLENDINDICES_INDEX4,
	PAVE_INSTANCING_BLENDINDICES_INDEX5,
	PAVE_INSTANCING_BLENDINDICES_INDEX6,
	PAVE_INSTANCING_BLENDINDICES_INDEX7,
	
	PAVE_INSTANCING_COLOR_INDEX0,
	PAVE_INSTANCING_COLOR_INDEX1,
	PAVE_INSTANCING_COLOR_INDEX2,
	PAVE_INSTANCING_COLOR_INDEX3,
	PAVE_INSTANCING_COLOR_INDEX4,
	PAVE_INSTANCING_COLOR_INDEX5,
};
