enum SpawnEditProp
{
	SpawnEditProp_ErrorMessage,

	// Common ( Character, Group ���� )
	SpawnEditProp_SelectionType,
	SpawnEditProp_SelectionCount,
	SpawnEditProp_SpawnPlacementKey,
	SpawnEditProp_SectorXZ,
	SpawnEditProp_KeyInSector,
	SpawnEditProp_IsSpawnOnBoot,
#ifdef SUPPORT_REALTIME_BASE_SPAWN
	SpawnEditProp_IsSpawnOnRealTime,
#endif
	SpawnEditProp_IsMainChannelSync,
	SpawnEditProp_SpawnQuantity,
	SpawnEditProp_SpawnDelayTimeOnBoot,
	SpawnEditProp_SpawnVariableTimeOnBoot,
	SpawnEditProp_SpawnDelayTime,
	SpawnEditProp_SpawnVariableTime,
	SpawnEditProp_ReSpawnNumber,
	SpawnEditProp_Position,
	SpawnEditProp_Direction,
	SpawnEditProp_SpawnRange,
	SpawnEditProp_StableKey,
	SpawnEditProp_StableOutKey,
	SpawnEDitProp_TerritoryKey,

	// Character ���� [ SpawnType_Normal.���� ]
	SpawnEditProp_CharacterKey,
	SpawnEditProp_CharacterName,
	SpawnEditProp_CharacterDisplayName,
	SpawnEditProp_Event_Object_Key,
	SpawnEditProp_InterAction_Event_Object_Key,
	SpawnEditProp_LiveWorld_Event_Key,
	SpawnEditProp_ActionIndex,
	SpawnEditProp_TeamNo,
	SpawnEditProp_DialogIndex,
	SpawnEditProp_DialogUpdateTime,
	SpawnEditProp_IsNpcGoHome,
	SpawnEditProp_HousePosition,
	SpawnEditProp_PositionIndex,
	SpawnEditProp_UseCustomData,
	SpawnEditProp_Aggressive,
	SpawnEditProp_DetectDistance,
	SpawnEditProp_ChaseDistance,
	SpawnEditProp_CheckLevel,
	SpawnEditProp_RandomMoveDistance,
	SpawnEditProp_RandomMoveCycle,
	SpawnEditProp_MoveDestinationMax,
	SpawnEditProp_Hp,
	SpawnEditProp_DDD,
	SpawnEditProp_DHIT,
	SpawnEditProp_DDV,
	SpawnEditProp_HDDV,
	SpawnEditProp_DPV,
	SpawnEditProp_HDPV,
	SpawnEditProp_RDD,
	SpawnEditProp_RHIT,
	SpawnEditProp_RDV,
	SpawnEditProp_HRDV,
	SpawnEditProp_RPV,
	SpawnEditProp_HRPV,
	SpawnEditProp_MDD,
	SpawnEditProp_MHIT,
	SpawnEditProp_MDV,
	SpawnEditProp_HMDV,
	SpawnEditProp_MPV,
	SpawnEditProp_HMPV,
	SpawnEditProp_UseCustomSpawnData,
	SpawnEditProp_SpawnConditionType,
	SpawnEditProp_SpawnStartHour,
	SpawnEditProp_SpawnEndHour,
	SpawnEditProp_BoneFileName,
	SpawnEditProp_MeshFileName,
	SpawnEditProp_AnimationFileName,

	// Group ���� [ SpawnType_Normal.�׷� ]
	SpawnEditProp_Group_Key,
	SpawnEditProp_Group_EntityQuantity,
	SpawnEditProp_Group_IsOverlapable,
	SpawnEditProp_Group_Char0,
	SpawnEditProp_Group_Char1,
	SpawnEditProp_Group_Char2,
	SpawnEditProp_Group_Char3,
	SpawnEditProp_Group_Char4,
	SpawnEditProp_Group_Char5,
	SpawnEditProp_Group_Char6,
	SpawnEditProp_Group_Char7,
	SpawnEditProp_Group_CharMax,				// ���� ������ ���� ( GroupChar �� ���� �����ϱ� ���� �ʿ��� )

	//Spawn Waypoint �� ��ø ����.
	SpawnEditProp_SpawnWaypointType = SpawnEditProp_Group_CharMax,

};
